version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-app-serverHost
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
      - DOCKERHUB_TOKEN=${DOCKERHUB_TOKEN}
    command: ["sh", "-c", "echo 'Starting Vite preview server...' && npm run preview"]