version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-app-serverHost
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    command: ["sh", "-c", "echo 'Starting Vite preview server...' && npm run preview"]
