services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-app-serverHost
    ports:
      - "5173:5173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
