name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache npm dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Install Docker credential helper
      run: |
        mkdir -p ~/.docker
        curl -fsSL https://github.com/docker/docker-credential-helpers/releases/download/v0.6.4/docker-credential-actions-v0.6.4-linux-amd64.tar.gz | tar xz -C /usr/local/bin
        echo '{"credsStore": "actions"}' > ~/.docker/config.json

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ vars.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context: .
       platforms: linux/amd64,linux/arm64
       push: true
       tags: jezzcomputers/githubaction:latest
       cache-from: type=local,src=/tmp/.buildx-cache
       cache-to: type=local,dest=/tmp/.buildx-cache

  deploy:
    needs: build
    name: Deploy to VPS via Tailscale
    runs-on: ubuntu-latest
    steps:
    - name: Connect Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_AUTHKEY_SECRET }}
        tags: tag:ci

    - name: SSH via Tailscale
      env:
        PI_PASSWORD: ${{ secrets.PI_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        ssh -o "StrictHostKeyChecking=no" jeremy@${{ vars.TAILSCALE_IP }} "
        echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin && \
        docker stop app || true && \
        docker rm app || true && \
        docker image prune -af && \
        docker pull jezzcomputers/githubaction:latest && \
        docker run -d --name app --restart unless-stopped jezzcomputers/githubaction:latest && \
        exit"

    - name: Cleanup
      run: |
        sudo rm -rf ~/.ssh
        sudo tailscale down
        sudo tailscale logout
        unset PI_PASSWORD