name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ vars.DOCKERHUB_USERNAME }}
       password: ${{ vars.DOCKERHUB_TOKEN }}

    - name: Configure Docker credentials
      run: echo "${{ vars.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: jezzcomputers/githubaction:latest

  deploy:
    needs: build
    name: Deploy image on OCI compute instance
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      run: ssh-keyscan -H ssh.jeremysprague.tech > ~/.ssh/known_hosts
    - name: connect and pull
      run: |
        sshpass -p "${{ vars.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no jeremy@ssh.jeremysprague.tech \
        "cd ${{ vars.WORK_DIR }} && sudo docker compose down app && sudo docker compose pull && sudo docker compose build && sudo docker compose up app -d && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
