name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ vars.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Configure Docker credentials
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: jezzcomputers/githubaction:latest

  deploy:
    needs: build
    name: Deploy image on OCI compute instance
    runs-on: ubuntu-latest
    steps:
    - name: Install Tailscale
      run: |
        sudo apt-get update
        sudo apt-get install -y tailscale
    - name: Join Tailscale network
      run: tailscale up --auth-key=tskey-${{ secrets.TAILSCALE_AUTHKEY }}
    - name: SSH via Tailscale
      env:
        PI_PASSWORD: ${{ secrets.PI_PASSWORD }}
      run: |
        sshpass -p "$PI_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null jeremy@${{ vars.TAILSCALE_IP }} \
        "cd ${{ vars.WORK_DIR }} && sudo docker compose down app && sudo docker compose pull && sudo docker compose build && sudo docker compose up app -d && exit"
    - name: Cleanup
      run: |
        rm -rf ~/.ssh
        tailscale down
        unset PI_PASSWORD