name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ vars.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Configure Docker credentials
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: jezzcomputers/githubaction:latest

  deploy:
    needs: build
    name: Deploy image on OCI compute instance
    runs-on: ubuntu-latest
    steps:
    - name: Add Tailscale repository and keyring
      run: |
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
        curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
    - name: Install Tailscale
      run: |
        sudo apt-get update
        sudo apt-get install -y tailscale
    - name: Join Tailscale network
      run: sudo tailscale up --auth-key=${{ secrets.TAILSCALE_AUTHKEY }} --ssh --accept-routes --advertise-routes
    - name: SSH via Tailscale
      env:
        PI_PASSWORD: ${{ secrets.PI_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        sshpass -p "$PI_PASSWORD" ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null jeremy@${{ vars.TAILSCALE_IP }} \
        "echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin && docker stop app || true && docker rm app || true && docker pull jezzcomputers/githubaction:latest && docker run -d --name app jezzcomputers/githubaction:latest && exit"
    - name: Cleanup
      run: |
        sudo rm -rf ~/.ssh
        sudo tailscale down
        sudo unset PI_PASSWORD